# 自動關閉不活躍的問題和拉取請求功能
name: "Close stale issues and PRs"

on:
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch: # 可以手動執行此 action

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 1
          days-before-issue-close: 1

          days-before-pr-stale: 1
          days-before-pr-close: 1

          stale-issue-label: "stale"
          stale-pr-label: "stale"

          start-date: "2020-04-18T00:00:00Z" # ISO 8601 or RFC 2822

          stale-issue-message: "Bumping this issue because it has been open for 7 days with no activity. Closing automatically in 7 days unless it becomes active again."
          close-issue-message: "Closing due to inactivity."

          stale-pr-message: "Bumping this pull request because it has been open for 7 days with no activity. Closing automatically in 7 days unless it becomes active again."
          close-pr-message: "Closing due to inactivity."

          repo-token: ${{ secrets.GITHUB_TOKEN }}
