name: CodeQL Analysis

on:
  workflow_dispatch: # 可以手動執行此 action

jobs:
  codeql:
    name: Analyze Code
    runs-on: ubuntu-latest
    permissions:
      security-events: write # 允許上傳安全事件

    steps:
      # 拉取程式碼
      - name: Checkout repository
        uses: actions/checkout@v4

      # 初始化 CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java, javascript

      - uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "21"
          cache: "maven"

      - name: Build with Maven
        run: ./mvnw clean compile dependency:copy-dependencies

      # 執行 CodeQL 分析
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
