name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          # Creates a draft release. Defaults to false(false表是直接發佈、true表是草稿)
          # draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
