name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 取得 Tag 所屬的分支
        id: branch
        env:
          BRANCH_PATTERN: "develop"
        run: |
          # 取得所有分支
          git fetch --all 
          # 取得 Tag 所屬的分支
          BRANCH_NAME=$(git branch -r --contains ${{ github.sha }} | grep -Eo '(${{env.BRANCH_PATTERN}})' | head -n 1)

          echo "Tag Commit: ${{ github.sha }}"
          echo "對應的分支: $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
