name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get branch name
        id: branch
        run: |
          git branch -r --contains ${{ github.sha }}

      - name: Set Test
        run: |
          echo "VV=>${{ steps.branch.outputs.BRANCH_NAME }}"
          echo "VV=>$BRANCH_NAME"
