name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 取得 Tag 所屬的分支
        run: |
          TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref_name }})
          BRANCH_NAME=$(git branch -r --contains $TAG_COMMIT | grep -Eo 'origin/(main|develop)' | sed 's/origin\///' | head -n 1)

          echo "Tag Commit: $TAG_COMMIT"
          echo "對應的分支: $BRANCH_NAME"

      - name: Set Test
        run: |
          echo "VV=>${{ steps.branch.outputs.BRANCH_NAME }}"
          echo "VV=>$BRANCH_NAME"
