name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get branch name
        id: branch
        run: |
          BRANCH_NAME=$(git branch -r --contains ${{ github.sha }} | grep -Eo '(master)' | head -n 1)
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: skip if not master
        if: steps.branch.outputs.BRANCH_NAME == ''
        run: |
          echo "Not on master branch, exiting"
          exit 0

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true # true 產生 release notes
          prerelease: false # false 正式發佈版本 (Stable Release
          draft: false # false 直接發佈
