name: Test Telegram Bot

on:
  workflow_dispatch: # 可以手動執行此 action

jobs:
  test-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup credentials
        run: |
          echo '${{ secrets.GMAIL_SERVICE_ACCOUNT }}' > service-account.json

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: GitHub Action Result
          body: Job completed successfully!
          to: vancetang@gmail.com
          from: GitHub Actions
