name: Send Email Notification

on:
  workflow_dispatch: # 可以手動執行此 action

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: GitHub Action Notification
          body: Workflow completed successfully!
          to: vance.tang@gmail.com
          from: GitHub Actions
