name: PR Update develop

on:
  push:
    branches:
      - master

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update develop
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git checkout develop
          git pull origin master
          git push origin develop
