name: PR Auto Merge

on:
  push:
    branches:
      - master

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action[bot]"
          git config --global user.email "actions[bot]@users.noreply.github.com"

      - name: Merge master into develop
        run: |
          git checkout develop
          git merge master
          git push origin develop
