name: Sync master to develop

on:
  push:
    branches:
      - master # 當 master 分支有 push 事件時觸發

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 拉取完整歷史紀錄

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Sync with develop
        run: |
          git fetch origin
          git checkout develop
          git merge origin/master --no-edit
          git push origin develop
