name: Create Release Please

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #   - name: Checkout
      #     uses: actions/checkout@v4

      - name: 依條件設定分支名稱
        id: branch
        env:
          ALLOWED_BRANCHES: "master"
        run: |
          # 取得所有分支
          git fetch --all 
          # 依條件取得分支名稱
          BRANCH_NAME=$(git branch -r --contains ${{ github.sha }} | grep -Eo '(${{env.ALLOWED_BRANCHES}})' | head -n 1)
          echo "Tag Commit: ${{ github.sha }}"
          echo "允分支名稱: ${{env.ALLOWED_BRANCHES}}"
          echo "======================================="
          git branch -r --contains ${{ github.sha }}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Release
        uses: googleapis/release-please-action@v4
        if: startsWith(github.ref, 'refs/tags/') && steps.branch.outputs.BRANCH_NAME != ''
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.GITHUB_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: simple
