name: Reset Labels

on:
  issues:
    types: [opened, edited]

jobs:
  reset-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Reset and Set Labels with Color and Description
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // 定義標籤及其顏色與描述
            const labels = [
              {
                "name": "bug",
                "color": "d73a4a",
                "description": "Something isn't working"
              },
              {
                "name": "documentation",
                "color": "0075ca",
                "description": "Improvements or additions to documentation"
              },
              {
                "name": "duplicate",
                "color": "cfd3d7",
                "description": "This issue or pull request already exists"
              },
              {
                "name": "enhancement",
                "color": "a2eeef",
                "description": "Feature request or improvement suggestion to enhance the functionality"
              },
              {
                "name": "feature",
                "color": "dac387",
                "description": "New Feature Request"
              },
              {
                "name": "good first issue",
                "color": "7057ff",
                "description": "Good for newcomers"
              },
              {
                "name": "help wanted",
                "color": "008672",
                "description": "Extra attention is needed"
              },
              {
                "name": "invalid",
                "color": "e4e669",
                "description": "This doesn't seem right"
              },
              {
                "name": "question",
                "color": "d876e3",
                "description": "Further information is requested"
              },
              {
                "name": "testing",
                "color": "f9d0c4",
                "description": "Used to mark features that need testing or are currently being tested"
              },
              {
                "name": "wip",
                "color": "f4a261",
                "description": "Work in Progress"
              },
              {
                "name": "wontfix",
                "color": "ffffff",
                "description": "This will not be worked on"
              }
            ];

            // 新增或更新標籤
            for (const label of labels) {
              try {
                await github.rest.issues.createLabel({
                  owner,
                  repo,
                  name: label.name,
                  color: label.color,
                  description: label.description
                });
                console.log(`Label "${label.name}" created or updated.`);
              } catch (error) {
                // 如果標籤已經存在，則忽略錯誤
                console.log(`Label "${label.name}" already exists.`);
              }
            }

            // 設定新的標籤到 Issue
            const labelNames = labels.map(label => label.name);
            await github.issues.setLabels({
              owner,
              repo,
              issue_number,
              labels: labelNames
            });

            console.log(`Updated labels for issue #${issue_number}`);
