name: SonarCloud Scan

on:
  workflow_dispatch: # 可以手動執行此 action

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      # 1. 檢查出代碼庫
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 安裝 Java 環境
      - uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "21"
          cache: "maven"

      # 3. 設定 SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 自動提供
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # 需要在 GitHub Secrets 中設置
