name: Sync Master into Develop

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  merge_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: 同步 master 到 develop
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git pull origin master
          git push origin develop
