name: Sync Master to Develop

on:
  pull_request:
    types: [closed]
    branches:
      - master # 監聽合併到 master 的 PR

permissions:
  contents: write
  pull-requests: write

jobs:
  sync_job:
    if: github.event.pull_request.merged == true # 確保 PR 被合併
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Develop Branch
        uses: actions/checkout@v4
        with:
          ref: develop # 檢出 develop 分支

      - name: Merge Master into Develop
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git pull --rebase origin master  # 從 master 獲取最新變更
          git push origin develop  # 將變更推送到 develop 分支
