name: Sync Master into Develop

on:
  pull_request:
    types:
      - closed
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  merge_job:
    if: github.event.pull_request.merged == true # 確保是合併的拉取請求
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: 檢查是否為合併
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git pull origin master
          git push origin develop
