name: Sync Master into Develop(同步)

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: 檢查是否為合併
        if: github.event.head_commit.message == 'Merge pull request'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git pull origin master
          git push origin develop
