name: Run Java

on:
  workflow_dispatch: # 可以手動執行此 action

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "21"
      - run: java com.vance.demo.Test.java
