name: Run Java

on:
  workflow_dispatch: # 可以手動執行此 action

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "21"
          cache: "maven"

      - name: Build with Maven
        run: mvn clean package

      - name: Get generated jar filename
        id: jar-filename
        run: |
          JAR_FILE=$(ls target/*.jar | head -n 1)
          echo "Jar file: $JAR_FILE"
          echo "::set-output name=jar-file::$JAR_FILE"

      - name: Print jar filename
        run: |
          echo "Generated jar filename: ${{ steps.jar-filename.outputs.jar-file }}"

      - name: Run Java
        run: java -cp ./target/${{ steps.jar-filename.outputs.jar-file }} com.vance.demo.tool.Test
