name: Translate README(VANCE)

on:
  workflow_dispatch: # 可以手動執行此 action

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' # 確保只在 develop 分支運行
    steps:
      - uses: actions/checkout@v4
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages
      - name: Adding README - English
        uses: vancetang/translate-readme@v1.0.0
        with:
          input: docs/PULL_REQUEST_TEMPLATE.md
          LANG: en
